name: moviestand
version: 0.0.1
author: Josep Sayol <josep.sayol@gmail.com>
dependencies:
  angular2: 2.0.0-alpha.52
  browser: ^0.10.0
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
  - angular2:
      entry_points: web/main.dart
  - dart_to_js_script_rewriter
